// Domain Layer Exports

// Entities
export {
    Character,
    Npc,
    InventoryItem,
    WorldItem,
} from './entities';
export type {
    CharacterData,
    NpcData,
    InventoryItemData,
    WorldItemData,
    ItemType,
    ItemGrade,
} from './entities';

// Value Objects
export {
    Position,
    Vitals,
    BaseStats,
    CombatStats,
    Experience,
    ObjectId,
    NpcTemplateId,
    ItemTemplateId,
    SkillId,
    PositionError,
    VitalsError,
    ExperienceError,
    IdentityError,
} from './value-objects';
export type {
    PositionData,
    VitalsData,
    CharacterStatsData,
    CombatStatsData,
    ExperienceData,
    ObjectIdData,
    NpcTemplateIdData,
    ItemTemplateIdData,
    SkillIdData,
} from './value-objects';

// Events
export {
    BaseDomainEvent,
    CharacterEnteredGameEvent,
    CharacterStatsChangedEvent,
    CharacterLevelUpEvent,
    CharacterPositionChangedEvent,
    CharacterTargetChangedEvent,
    CharacterSkillsUpdatedEvent,
    InventoryItemAddedEvent,
    InventoryItemRemovedEvent,
    InventoryItemUpdatedEvent,
    AdenaChangedEvent,
    NpcSpawnedEvent,
    NpcDespawnedEvent,
    NpcInfoUpdatedEvent,
    PlayerSpawnedEvent,
    PlayerDespawnedEvent,
    ItemDroppedEvent,
    ItemPickedUpEvent,
    AttackEvent,
    SkillUseEvent,
    TargetDiedEvent,
    ConnectedEvent,
    DisconnectedEvent,
    AuthenticationSuccessEvent,
    AuthenticationFailedEvent,
    CharacterSelectedEvent,
    StateChangedEvent,
    ChatMessageReceivedEvent,
    ChatMessageSentEvent,
    SystemMessageReceivedEvent,
    ConnectionPhaseChangedEvent,
} from './events';
export type {
    DomainEvent,
    EventHandler,
    Subscription,
    CharacterEnteredGamePayload,
    CharacterStatsChangedPayload,
    CharacterLevelUpPayload,
    CharacterPositionChangedPayload,
    CharacterTargetChangedPayload,
    CharacterSkillsUpdatedPayload,
    SkillInfo,
    InventoryItemAddedPayload,
    InventoryItemRemovedPayload,
    InventoryItemUpdatedPayload,
    AdenaChangedPayload,
    NpcSpawnedPayload,
    NpcDespawnedPayload,
    NpcInfoUpdatedPayload,
    PlayerSpawnedPayload,
    PlayerDespawnedPayload,
    ItemDroppedPayload,
    ItemPickedUpPayload,
    AttackPayload,
    SkillUsePayload,
    TargetDiedPayload,
    ConnectedPayload,
    DisconnectedPayload,
    AuthenticationSuccessPayload,
    AuthenticationFailedPayload,
    CharacterSelectedPayload,
    StateChangedPayload,
    ConnectionPhaseChangedPayload,
    ChatChannel,
    ChatMessagePayload,
    SystemMessagePayload,
} from './events';

// Repositories (Ports)
export {
    ICharacterRepository,
    CharacterRepositoryError,
    IWorldRepository,
    WorldRepositoryError,
    IInventoryRepository,
    InventoryRepositoryError,
    IConnectionRepository,
    ConnectionPhase,
    type ConnectionState,
    ConnectionRepositoryError,
} from './repositories';
export type {
    NearbyFilter,
    WorldSnapshot,
    InventoryState,
} from './repositories';
